---
- name: Get tokens
  include_tasks:
    file: "tasks/token.yml"

# Helper variable for json query
# https://stackoverflow.com/questions/46038985/ansible-pass-a-variable-in-a-json-query-filter
- set_fact:
    json_query_for_token: '[?name==`{{ px_ss_api_token }}`].id'
    json_query_for_token_keys: '[?name==`{{ px_ss_api_token }}`].keys[].name'
- set_fact:
    px_ss_api_token_id: "{{ px_ss_api_tokens_get.json | community.general.json_query(json_query_for_token) | join(' ') }}"
    px_ss_api_token_keys: "{{ px_ss_api_tokens_get.json | community.general.json_query(json_query_for_token_keys) }}"

- name: Enroll certificate
  block:
  - name: Create key and CSR
    ansible.builtin.uri:
      url: "{{ px_ss_api_uri }}/api/v1/tokens/{{ px_ss_api_token_id }}/keys-with-csrs"
      method: POST
      body_format: json
      body:
        key_label: "{{ key_type }}-{{ item.member_code }}"
        csr_generate_request:
          key_usage_type: "{{ key_usage_type }}"
          ca_name: "{{ px_ss_api_ca }}"
          csr_format: "PEM"
          member_id: "{{ px_ss_api_instance }}:{{ item.member_class }}:{{ item.member_code }}"
          subject_field_values:
            CN: "{{ item.member_code }}"
      status_code:
        - 200
        - 201
        - 409
      headers:
        Content-Type: application/json
        Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
      validate_certs: "{{ px_ss_api_validate_certs }}"
    register: px_ss_api_token_create_keys_with_csrs
    changed_when: px_ss_api_token_create_keys_with_csrs.status == 200

  - set_fact:
      key_id: "{{ px_ss_api_token_create_keys_with_csrs.json.key.id }}"
      csr_id: "{{ px_ss_api_token_create_keys_with_csrs.json.csr_id }}"

  - name: Fetch CSR
    ansible.builtin.uri:
      url: "{{ px_ss_api_uri }}/api/v1/keys/{{ key_id }}/csrs/{{ csr_id }}?csr_format=PEM"
      method: GET
      body_format: json
      return_content: true
      status_code:
        - 200
      headers:
        Content-Type: application/json
        Accept: application/octet-stream
        Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
      validate_certs: "{{ px_ss_api_validate_certs }}"
    register: px_ss_api_csr
    changed_when: true

  - name: Request certificate
    uri:
      url: "{{ px_ss_api_ca_enrollment_endpoint }}"
      method: POST
      body_format: form-multipart
      body:
        user: "{{ key_type }}-{{ item.member_code }}"
        password: "{{ item.enrollment_token }}"
        pkcs10req: "{{ px_ss_api_csr.content }}"
        resulttype: "4"
      return_content: true
    register: px_ss_api_cert
    changed_when: true

  - name: Import certificate
    ansible.builtin.uri:
      url: "{{ px_ss_api_uri }}/api/v1/token-certificates"
      method: POST
      body:
        "{{ px_ss_api_cert.content }}"
      status_code:
        - 200
        - 201
        - 409
      headers:
        Content-Type: application/octet-stream
        Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
      validate_certs: "{{ px_ss_api_validate_certs }}"
    register: px_ss_api_token_import_certificate
    changed_when: true
  when: "key_type + '-' + item.member_code not in px_ss_api_token_keys"
