---
- name: Configure security server
  block:
    - name: Check if we should create an API key
      set_fact:
        px_ss_api_do_create_api_key: true
      when: px_ss_api_key == "" and px_ss_api_key_auto_create == true

    - name: Create API key if necessary
      uri:
        url: "{{ px_ss_api_uri }}/api/v1/api-keys"
        user: "{{ px_ui_user_name }}"
        password: "{{ px_ui_user_password }}"
        method: POST
        body:
          - XROAD_SECURITY_OFFICER
          - XROAD_REGISTRATION_OFFICER
          - XROAD_SERVICE_ADMINISTRATOR
          - XROAD_SECURITYSERVER_OBSERVER
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: "{{ px_ss_api_validate_certs }}"
      register: px_ss_api_key_created
      when: px_ss_api_do_create_api_key == true
      changed_when: px_ss_api_key_created.status == 200

    - name: Set px_ss_api_key and px_ss_api_key_id
      set_fact:
        px_ss_api_key: "{{ px_ss_api_key_created.json['key'] }}"
        px_ss_api_key_id: "{{ px_ss_api_key_created.json['id'] }}"
      when: px_ss_api_do_create_api_key == true

    # Cleanup orphaned keys and CSRs from previous runs.
    - name: Cleanup orphan objects
      include_tasks:
        file: "tasks/clean.yml"

    - name: Register security server
      include_tasks:
        file: "tasks/register.yml"

    - name: Create clients
      include_tasks:
        file: "tasks/client.yml"
        apply:
          tags:
            - px-ss-api-clients
      tags:
        - px-ss-api-clients
      loop: "{{ px_ss_api_clients }}"

    - name: Create services
      include_tasks:
        file: "tasks/service.yml"
        apply:
          tags:
            - px-ss-api-services
      tags:
        - px-ss-api-services
      loop: "{{ px_ss_api_clients | subelements('services', skip_missing=True) }}"

    - name: Create acls
      include_tasks:
        file: "tasks/acl.yml"
        apply:
          tags:
            - px-ss-api-acls
      tags:
        - px-ss-api-acls
      loop: "{{ px_ss_api_acls }}"
      loop_control:
        loop_var: acl_item

  always:
    - name: Destroy API key
      uri:
        url: "{{ px_ss_api_uri }}/api/v1/api-keys/{{ px_ss_api_key_id }}"
        user: "{{ px_ui_user_name }}"
        password: "{{ px_ui_user_password }}"
        method: DELETE
        validate_certs: "{{ px_ss_api_validate_certs }}"
      register: px_ss_api_key_destroyed
      when: px_ss_api_do_create_api_key == true
      changed_when: px_ss_api_key_destroyed.status == 200
