---
- name: Get tokens
  include_tasks:
    file: "tasks/token.yml"

- name: Query authentication certificate
  set_fact:
    px_ss_api_authentication: "{{ px_ss_api_tokens_get | community.general.json_query(json_query_authentication) | flatten }}"
  var:
    json_query_authentication: "json[].keys[?usage=='AUTHENTICATION'].certificates[]"

- name: Activate authentication certificate
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/token-certificates/{{ px_ss_api_authentication[0].certificate_details.hash }}/activate"
    method: PUT
    body_format: json
    status_code:
      - 204
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_register
  when: 'px_ss_api_authentication[0].active == false'
  changed_when: px_ss_register.status == 204

- name: Register authentication certificate
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/token-certificates/{{ px_ss_api_authentication[0].certificate_details.hash }}/register"
    method: PUT
    body_format: json
    body:
      address: "{{ px_ss_public_endpoint }}"
    status_code:
      - 204
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_register
  when: 'px_ss_api_authentication[0].status == "SAVED"'
  changed_when: px_ss_register.status == 204

# Refresh available tokens
# Helper variable for json query
# https://stackoverflow.com/questions/46038985/ansible-pass-a-variable-in-a-json-query-filter
- set_fact:
    json_query_registration_status: "json[].keys[?usage=='AUTHENTICATION'].certificates[*].status"

- name: Check registration status
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/tokens"
    method: GET
    body_format: json
    status_code:
      - 200
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_registration_status
  until: "'REGISTERED' in px_ss_registration_status | community.general.json_query(json_query_registration_status) | flatten"
  retries: 5
  delay: 60
