# https://github.com/nordic-institute/X-Road/blob/develop/src/proxy-ui-api/src/main/resources/openapi-definition.yaml
---
- name: Create a service
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/clients/{{ px_ss_api_instance }}:{{ item.0.member_class }}:{{ item.0.member_code }}:{{ item.0.subsystem_code }}/service-descriptions"
    method: POST
    body:
      url: "{{ item.1.url }}"
      rest_service_code: "{{ item.1.rest_service_code | default(omit) }}"
      ignore_warnings: false
      type: "{{ item.1.type }}"
    status_code:
      - 201
      - 409
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_service_created
  changed_when: px_ss_api_service_created.status == 201

- name: Get service information
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/clients/{{ px_ss_api_instance }}:{{ item.0.member_class }}:{{ item.0.member_code }}:{{ item.0.subsystem_code }}/service-descriptions"
    method: GET
    status_code:
      - 200
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_services_get
  changed_when: false

- name: Select the service-description from the list
  set_fact:
    px_ss_api_service_this: "{{ px_ss_api_services_get | json_query(px_ss_api_service_this_query) }}"
  vars:
    # first service-description that matches given url
    px_ss_api_service_this_query: "json[?url=='{{ item.1.url }}'] | [0]"

- name: Enable service
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/service-descriptions/{{ px_ss_api_service_this.id }}/enable"
    method: PUT
    status_code:
      # in the OpenAPI document it's 204
      - 200
      - 204
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_service_enabled
  when: item.1.enabled == true and px_ss_api_service_this.disabled == true
  changed_when: px_ss_api_service_enabled.status == 200

- name: Disable service
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/service-descriptions/{{ px_ss_api_service_this.id }}/disable"
    method: PUT
    status_code:
      # in the OpenAPI document it's 204
      - 200
      - 204
    body_format: json
    body:
      disabled_notice: "{{ item.1.disabled_notice }}"
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_service_disabled
  when: item.1.enabled == false and px_ss_api_service_this.disabled == false
  changed_when: px_ss_api_service_disabled.status == 200

- name: Set service URL for service code
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/services/{{ px_ss_api_instance }}:{{ item.0.member_class }}:{{ item.0.member_code }}:{{ item.0.subsystem_code }}:{{ service_url_item.service_code }}"
    method: PATCH
    body_format: json
    body:
      url: "{{ service_url_item.service_code_url }}"
      timeout: "{{ timeout | default(60) }}"
      ssl_auth: "{{ ssl_auth | default(false) }}"
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_service_url_for_service_code
  loop: "{{ item.1.service_codes }}"
  loop_control:
    loop_var: service_url_item
  when: service_url_item.service_code_url is defined
