# https://github.com/nordic-institute/X-Road/blob/develop/src/proxy-ui-api/src/main/resources/openapi-definition.yaml
---
- name: Add service clients
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/services/{{ px_ss_api_instance }}:{{ item.0.member_class }}:{{ item.0.member_code }}:{{ item.0.subsystem_code }}:{{ item.1.service_code}}/service-clients"
    method: POST
    body:
      items: "{{ item.1.service_clients }}"
    status_code:
      # actually returns 200
      - 200
      - 201
      - 409
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_add_service_clients
  changed_when: px_ss_api_add_service_clients.status == 200 or px_ss_api_add_service_clients.status == 201

- name: Get service clients
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/services/{{ px_ss_api_instance }}:{{ item.0.member_class }}:{{ item.0.member_code }}:{{ item.0.subsystem_code }}:{{ item.1.service_code}}/service-clients"
    method: GET
    status_code:
      - 200
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_get_service_clients

# Compare service clients in security server with what we have in ansible
# delete them in next step
- name: Identify service clients to delete
  set_fact:
    service_clients_to_delete: "{{ px_ss_api_get_service_clients | community.general.json_query(json_query_service_clients) | difference(item.1.service_clients) }}"
  vars:
    json_query_service_clients: "json[].{id: id}"

- name: Delete service clients
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/services/{{ px_ss_api_instance }}:{{ item.0.member_class }}:{{ item.0.member_code }}:{{ item.0.subsystem_code }}:{{ item.1.service_code}}/service-clients/delete"
    method: POST
    body:
      items: "{{ service_clients_to_delete }}"
    status_code:
      # actually returns 200
      - 200
      - 204
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_delete_service_clients
  changed_when: px_ss_api_delete_service_clients.status == 200 or px_ss_api_delete_service_clients.status == 204
  when: service_clients_to_delete | length > 0
