# https://github.com/nordic-institute/X-Road/blob/develop/src/proxy-ui-api/src/main/resources/openapi-definition.yaml
---
- name: Add service clients
  ansible.builtin.uri:
    url: "{{ px_ss_api_uri }}/api/v1/services/{{ px_ss_api_instance }}:{{ item.0.member_class }}:{{ item.0.member_code }}:{{ item.0.subsystem_code }}:{{ service_code_item.service_code}}/service-clients"
    method: POST
    body:
      items: "{{ service_code_item.service_clients }}"
    status_code:
      # actually returns 200
      - 200
      - 201
      - 409
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "X-Road-ApiKey token={{ px_ss_api_key }}"
    validate_certs: "{{ px_ss_api_validate_certs }}"
  register: px_ss_api_add_service_clients
  changed_when: px_ss_api_add_service_clients.status == 200 or px_ss_api_add_service_clients.status == 201
  loop: "{{ item.1.service_codes }}"
  loop_control:
    loop_var: service_code_item
